CREATE TABLE [dbo].[Usuario]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Nome] VARCHAR(30) NOT NULL, 
	[Email] VARCHAR(319) NOT NULL, 
    [Cpf] VARCHAR(11) NOT NULL, 
	[Telefone] VARCHAR(9) NOT NULL, 
	[Nascimento] DATETIME NOT NULL, 
	[Genero] VARCHAR(1) NOT NULL, 
	[Endereco] VARCHAR(255) NOT NULL, 
	[Pontos] VARCHAR(3) NOT NULL DEFAULT 0, 
    [Senha] VARCHAR(30) NOT NULL
)

--DROP TABLE [dbo].[Usuario]


CREATE TABLE [dbo].[Produto]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Nome] VARCHAR(255) NOT NULL, 
	[Preco] VARCHAR(319) NOT NULL, 
    [Descricao] VARCHAR(11) NOT NULL,
	[Ingrediente] VARCHAR(50) NOT NULL, 
)

CREATE TABLE [dbo].[Pedido]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Nome] VARCHAR(255) NOT NULL, 
	[Preco] VARCHAR(319) NOT NULL, 
    [Descricao] VARCHAR(11) NOT NULL, 
)